aliases:
  - &android
    components:
      - build-tools-23.0.1
      - android-23
      - extra-android-m2repository
      - extra-android-support
  
  - &android-cache
    directories:
      - ~/.cache/yarn
      - ~/.gradle/caches/modules-2
      - ~/.gradle/wrappers
  
  - &ios-cache
    directories:
      - ~/.rncache
      - ~/Library/Caches/Yarn
      - ~/Library/Caches/CocoaPods

  - &init-new-project
    |
      nvm install node
      yarn global add react-native-cli
      react-native init App
      cd App
      yarn add react-native-amap3d

jobs:
  include:
    - stage: "test js"
      language: node_js
      node_js: node
      cache: yarn

    - stage: "build test for example"
      language: android
      jdk: oraclejdk8
      android: *android
      before_cache:
        - rm ~/.gradle/caches/modules-2/modules-2.lock
      cache: *android-cache
      script:
        - nvm install node
        - yarn
        - cd android
        - ./gradlew build
        - ls -l app/build/outputs/apk

    - stage: "build test for example"
      language: objective-c
      osx_image: xcode9.1
      cache: *ios-cache
      before_install:
      script:
        - nvm install node
        - brew install yarn
        - yarn
        - cd ios
        - pod install
        - xcodebuild -workspace RNAMap3D.xcworkspace -scheme RNAMap3D -sdk iphonesimulator -quiet

    - stage: "build test for new project"
      language: android
      jdk: oraclejdk8
      android: *android
      before_cache:
        - rm ~/.gradle/caches/modules-2/modules-2.lock
      cache: *android-cache
      script:
        - *init-new-project
        - react-native link
        - cd android
        - ./gradlew build
        - ls -l app/build/outputs/apk

    - stage: "build test for new project"
      language: objective-c
      osx_image: xcode9.1
      cache: *ios-cache
      script:
        - brew install yarn
        - *init-new-project
        - cd ios
        - |
          cat << EOF > Podfile
            platform :ios, '8.0'
            target 'App' do
              pod 'React', path: '../node_modules/react-native', :subspecs => [
                'DevSupport',
              ]
              pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
              pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'
            end
          EOF
        - pod install
        - xcodebuild -workspace App.xcworkspace -scheme App -sdk iphonesimulator -quiet

stages:
  - "test js"
  - name: "build test for example"
    if: branch = master
  - name: "build test for new project"
    if: branch = release
